
[[main]]
  name = "科研"
  url = "/categories/科研/"
  weight = 1

  [[main]]
  name = "技术"
  url = "/categories/技术/"
  weight = 2

  [[main]]
  name = "生活"
  url = "/categories/生活/"
  weight = 3

[[main]]
  name = "文档"
  url = "/docs/"
  weight = 3

 [[main]]
  name = "札记"
  url = "/message/"
  weight = 4 

  [[main]]
  name = "关于我"
  url = "/authors/duyang/"
  weight = 5
